server {
    listen 80;
    server_name angeliquerobin.com;
    return 301 https://www.angeliquerobin.com$request_uri;
}

server {
    listen 80;
    server_name www.angeliquerobin.com _;
    root /usr/share/nginx/html;
    index accueil.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
